### ISSUE TITLE
Missing files and directories leading to workflow failure

### ISSUE THREAD

**Issue by VMois** [reanahub/reana-demo-cms-h4l#22] opened 2022-04-07 15:12 UTC
I have tried to run this analysis both via `launcher` and reana-client CLI but received the following error:

```
job: :
 WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
WARNING: There already exists /var/reana/users/000/workflows/000/cwl/outdir/0k038_2j/CMSSW_5_3_32 area for SCRAM_ARCH slc6_amd64_gcc472.
cp: cannot stat `../../../../code/HiggsExample20112012': No such file or directory
zsh:cd:6: no such file or directory: HiggsExample20112012/HiggsDemoAnalyzer
zsh:cd:8: no such file or directory: ../Level3
----- Begin Fatal Exception 07-Apr-2022 16:43:35 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named demoanalyzer_cfg_level3data.py
Exception Message:
python encountered the error: <type 'exceptions.IOError'>
[Errno 2] No such file or directory: 'demoanalyzer_cfg_level3data.py'
----- End Fatal Exception -------------------------------------------------
cp: cannot overwrite non-directory `/var/reana/users/000/workflows/000/cwl/outdir/be00up3t/code' with directory `/var/reana/users/000/workflows/000/cwl/outdir/0k038_2j/code'
cp: cannot overwrite non-directory `/var/reana/users/000/workflows/000/cwl/outdir/be00up3t/data' with directory `/var/reana/users/000/workflows/000/cwl/outdir/0k038_2j/data'

Error
```

Probably some files missing or some paths need to be corrected.

**Comment by tiborsimko** [comment] 2022-04-07 15:46
Also, we already have a ticket for CWL workflow not working, so we can close this issue as a duplicate of #17.

**Closed by tiborsimko** 2022-04-07 15:46 UTC
